// Define meeting states enum
// src/modules/meeting/meeting.state.ts

export enum MeetingState {
  MEETING_CREATED = "MEETING_CREATED",

  AI_JOINED = "AI_JOINED",

  WAITING_FOR_RESUME = "WAITING_FOR_RESUME",

  RESUME_UPLOADED = "RESUME_UPLOADED",
  RESUME_ANALYZED = "RESUME_ANALYZED",

  PREPARATION_TIME = "PREPARATION_TIME",

  INTERVIEW_STARTED = "INTERVIEW_STARTED",
  INTERVIEW_IN_PROGRESS = "INTERVIEW_IN_PROGRESS",

  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
